version: 2.1

slack-fail-post-step: &slack-fail-post-step
  post-steps:
    - slack/notify:
      custom: |
        {
          "blocks": [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": "Job Failed. :red_circle:",
                "emoji": true
              }
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Job*: ${CIRCLE_JOB}"
                }
              ]
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Project*:\\n$CIRCLE_PROJECT_REPONAME"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Branch*:\\n$CIRCLE_BRANCH"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Author*:\\n$CIRCLE_USERNAME"
                },
                {
                  "type": "mrkdwn",
                  "text": "*PR*:\\n$CIRCLE_PULL_REQUEST"
                }
              ],
              "accessory": {
                "type": "image",
                "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                "alt_text": "CircleCI logo"
              }
            },
            {
              "type": "actions",
              "elements": [
                {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "View Job"
                  },
                  "url": "${CIRCLE_BUILD_URL}"
                }
              ]
            }
          ]
        }
      event: fail

orbs:
  slack: circleci/slack@4.3.3

jobs:
  build:
    docker:
      - image: cimg/base:stable

    steps:
      - run:
          name: Success
          command: |
            exit 0
  last-job:
    docker:
      - image: cimg/base:stable

    steps:
      - run:
          name: Fail
          command: |
            exit 1

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          <<: *slack-fail-post-step
      - last-job:
          <<: *slack-fail-post-step
          requires:
            - build

